services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - dev

  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - dev

networks:
  dev:
    driver: bridge