services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: "654321"
    depends_on:
      - database
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "654321"
      POSTGRES_DB: corban